
name: 'Github_Actions'

on:
  push:
    branches:
      - 'main'
      - '*'
    paths:
      - 'dev/**'

concurrency: ${{ github.repository }}

jobs:
  dev_cicd:
    name: 'CICD Job dev'
    runs-on: 'ubuntu-latest'

    steps:

      - name: GIT Checkout
        id: 'git-checkout'
        uses: "actions/checkout@v4"
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Git credentials for Terraform module access
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init
        id: 'tf-init'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev
          terraform init
          pwd

      - name: Terraform Plan
        id: 'tf-plan'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev
          terraform plan


      - name: Terraform Apply
        id: 'tf-apply'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev
          terraform apply --auto-approve

      - name: Terraform Destroy
        id: 'tf-destroy'
        #if: github.event.inputs.destroy == 'true'  # Conditional execution
        if: |
          github.ref == 'refs/heads/destroy' 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev
          terraform destroy --auto-approve

    
      

#- name: Terraform Init and Apply
 # run: |
  #  terraform init
  #  terraform apply -auto-approve
  #env:
   # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
